backend: Remove recursion from metadata field separation logic
Simplify the data/metadata splitting code and get rid of the recursion
which was causing the following issue in prod:

   File "/usr/src/backend/api/api.py", line 262, in calc_changes
     results, results_meta = await store.get_results(user_id, test_name)
   File "/usr/src/backend/db/db.py", line 399, in get_results
     return separate_meta(results)
   File "/usr/src/backend/db/db.py", line 795, in separate_meta
     data, meta = separate_meta(doc[:-1])
   File "/usr/src/backend/db/db.py", line 795, in separate_meta
     data, meta = separate_meta(doc[:-1])
   File "/usr/src/backend/db/db.py", line 795, in separate_meta
     data, meta = separate_meta(doc[:-1])
   [Previous line repeated 957 more times]
   File "/usr/src/backend/db/db.py", line 782, in separate_meta
     if isinstance(doc, list):
 RecursionError: maximum recursion depth exceeded while calling a Python object