pulls/ fixes
Introduce new get_pulls_from_the_source() which uses aggregation
query directly on test_results. Avoids separate collection +
python code.

Small API breakage: add branch both as parameter and in result

And of course don't use user_id for PR

5 new test failures as MongoMock doesn't support aggregation.
Failures look like

ValueError: too many values to unpack (expected 2)